version: '3'


services:
  mongo:
    image: mongo:5.0.22-focal
    container_name: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ~/Desktop/coderhouse/mongo/docker/data:/data/db
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 3030:3030
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27018
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGO_ADMINPASSWORD: root
    links:
      - mongo
    networks:
      - mongo-network
networks:
  mongo-network:
    driver: bridge